# Generated by Django 5.2.7 on 2025-10-11 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Document title", max_length=255)),
                (
                    "file",
                    models.FileField(help_text="PDF file", upload_to="documents/"),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Document category (e.g., 'budowa', 'ogród', 'elektryka')",
                        max_length=100,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="Has this document been processed for embeddings?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Embedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_text",
                    models.TextField(help_text="Original text chunk from document"),
                ),
                (
                    "embedding_id",
                    models.CharField(
                        help_text="Supabase vector ID for this embedding",
                        max_length=100,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Metadata: page number, section, etc."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="knowledge.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding",
                "verbose_name_plural": "Embeddings",
                "db_table": "embeddings",
                "ordering": ["document", "id"],
            },
        ),
    ]
