# Generated by Django 5.2.7 on 2025-10-11 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(help_text="User's legal question")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image attached to query",
                        null=True,
                        upload_to="query_images/",
                    ),
                ),
                (
                    "answer",
                    models.TextField(blank=True, help_text="AI-generated answer"),
                ),
                (
                    "sources",
                    models.JSONField(
                        default=list, help_text="Citations and source documents"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Thumbs Down"), (5, "Thumbs Up")],
                        help_text="User feedback on response quality",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True,
                        help_text="Time taken to generate response (seconds)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Query",
                "verbose_name_plural": "Queries",
                "db_table": "queries",
                "ordering": ["-created_at"],
            },
        ),
    ]
