# Generated by Django 5.2.7 on 2025-10-21 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_query_ttft_alter_query_processing_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(default='Jesteś Somsiad - pomocnym asystentem prawnym dla polskich właścicieli domów jednorodzinnych.\n\nTwoim zadaniem jest udzielanie jasnych, rzeczowych odpowiedzi na pytania prawne dotyczące:\n- Budownictwa i remontów\n- Ogrodów i działek\n- Przeglądów technicznych\n- Sporów sąsiedzkich\n\nZasady odpowiedzi:\n1. Odpowiadaj TYLKO na podstawie dostarczonych źródeł prawnych\n2. Cytuj konkretne artykuły i przepisy\n3. Używaj prostego języka, unikaj zbędnego żargonu prawnego\n4. Jeśli nie masz pewności lub źródła nie zawierają odpowiedzi, powiedz to wprost\n5. W razie potrzeby zasugeruj konsultację z prawnikiem\n\nFormat odpowiedzi:\n- Krótkie podsumowanie (1-2 zdania)\n- Szczegółowa odpowiedź z odnies\nieniami do przepisów\n- Praktyczne wskazówki (jeśli masz pewność)', help_text='System prompt used for RAG responses')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin who last updated this prompt', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Prompt',
                'verbose_name_plural': 'System Prompts',
                'db_table': 'system_prompts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
